name: Publish Stable Build
on:
  workflow_call:
    secrets:
      PYPI_TOKEN:
        required: false
    inputs:
      runner:
        type: string
        default: "ubuntu-latest"
      version_file:
        type: string
        default: "version.py"
      setup_py:
        type: string
        default: "setup.py"
      branch:
        type: string
        default: ${{ github.ref }}
      publish_release:
        type: boolean
        default: True
      publish_pypi:
        type: boolean
        default: True
    outputs:
      version:
        description: Updated version
        value: ${{jobs.bump_version.outputs.version}}
jobs:
  bump_version:
    runs-on: ${{inputs.runner}}
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}
          path: action/package/
      - name: Checkout Scripts Repo
        uses: actions/checkout@v2
        with:
          path: action/github/
          repository: TigreGotico/gh-automations
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Declare Alpha stable
        id: version
        run: |
          python action/github/scripts/remove_alpha.py ${{ steps.version_bump.outputs.part }} --version-file action/package/${{ inputs.version_file }}
          echo ::set-output name=version::$(python action/package/${{ inputs.setup_py }} --version)

      - name: Push Version Change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Increment Version to ${{ steps.version.outputs.version }}
          branch: ${{ inputs.branch }}  # Ensure the correct branch is referenced
          repository: action/package/

  build_and_publish_pypi:
    if: ${{ always() && inputs.publish_pypi }}
    needs:
      - bump_version
    runs-on: ${{inputs.runner}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}
          path: action/package/
      - name: Checkout Scripts Repo
        uses: actions/checkout@v2
        with:
          path: action/github/
          repository: TigreGotico/gh-automations
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install Build Tools
        run: |
          python -m pip install build wheel
      - name: Build Distribution Packages
        run: |
          cd action/package
          python ${{ inputs.setup_py }} sdist bdist_wheel
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: action/package/dist/
          password: ${{secrets.PYPI_TOKEN}}

  tag_release:
    needs:
      - bump_version
    if: ${{ always() && inputs.publish_release }}
    runs-on: ${{inputs.runner}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}
          path: action/package/
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          tag: ${{needs.bump_version.outputs.version}}
          commit: ${{ github.ref }}
          prerelease: false
          generateReleaseNotes: true
